openapi: 3.0.1
info:
  title: Travel addict backend
  description: This is the Travel addict API
  version: 1.0.0
externalDocs:
  description: Github
  url: http://github.com/example
servers:
  - url: https://travel-addict-backend-server.herokuapp.com/
  - url: http://localhost:8080/
tags:
  - name: travel-addict
    description: Everything about travel addict

paths:
  /user:
    get:
      tags:
        - user
      summary: Get all user
      responses:
        "200":
          description: get all user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
    post:
      tags:
        - user
      summary: add a new user
      responses:
        "200":
          description: Successfully added a user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"

  /confirm/{confirmationCode}:
    post:
      tags:
        - user
      summary: confirm a user
      parameters:
        - in: path
          name: confirmationCode
          schema:
            type: string
          required: true
          description: confirmationCode of the entry for the user
      responses:
        "200":
          description: Successfully confirmed the user

  /reisen:
    get:
      tags:
        - reise
      summary: Get all reise
      responses:
        "200":
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SavedReise"
    post:
      tags:
        - reise
      summary: add a new reise
      responses:
        "200":
          description: Successfully added a reise
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Reise"

  /reisen/{uuid}:
    delete:
      tags:
        - reise
      summary: Deletes a reise by uuid
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
            format: uuid
          required: true
          description: uuid of the entry to delete
      responses:
        "204":
          description: successful operation
    put:
      tags:
        - reise
      summary: Replaces a reise with another by uuid
      responses:
        "204":
          description: Replaced Reise
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Reise"

  /loggedInUserEmail:
    get:
      tags:
        - loggedInUserEmail
      summary: Get email from current logged in user
      responses:
        "200":
          description: email from logged in user
          content:
            application/json:
              schema:
                type: string

  /login:
    post:
      tags:
        - login
      summary: Log in and get cookie for authentication
      responses:
        "200":
          description: Successfull request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Login"

components:
  schemas:
    User:
      type: object
      properties:
        email: 
          type: string
          format: email
        password:
          type: string

    Reise:
      type: object
      properties:
        name:
          type: string
        startDatum:
          type: string
          format: date-time
        endDatum:
          type: string
          format: date-time
        land:
          type: string
    SavedReise:
      allOf:
        - $ref: "#/components/schemas/Reise"
        - type: object
          required:
            - id
          properties:
            id:
              type: string
              format: uuid
    Login:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
